// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Blog = Collections['blogs']['schema']['_output']
export declare const blogs: Blog[]

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]

export type TIL = Collections['tils']['schema']['_output']
export declare const tils: TIL[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]

export type Design = Collections['designs']['schema']['_output']
export declare const designs: Design[]
