import type { Site } from "@/types";

export const siteConfig: Site = {
  name: "sehaj.works",
  title: "SEHAJ | Bringing Ideas to Reality",
  description: "Hi, I'm SEHAJ - Got ideas you are itching to bring to life? Let's collaborate and make it happen!",
  keywords: [
    "sehaj",
    "sehaj preet",
    "sehaj makkar",
    "sehaj works",
    "sehaj makkar 02",
    "portfolio",
    "sehaj portfolio",
    "sehaj 100x dev",
    "full stack developer",
    "designer",
    "web developer",
    "web designer",
    "react developer",
    "react designer",
    "next.js developer",
    "next.js designer",
    "sehaj makkar portfolio",
    "sehaj makkar website",
    "sehaj makkar portfolio website",
    "sehaj makkar portfolio website 2024",
    "sehaj makkar portfolio 2024",
    "sehaj",
    "sehaj in",
    "sehaj.in",
    "sehaj portfolio",
    "sehaj portfolio 2024",
    "sehaj portfolio website",
    "sehaj portfolio website 2024",
    "sehaj portfolio 2024 website",
    "sehaj portfolio 2024 website 2024",
    "sehaj portfolio 2024 website 2025",
    "sehaj portfolio 2025",
    "sehaj portfolio 2025 website",
    "sehaj portfolio 2025 website 2025",
  ],
  siteUrl: "https://sehaj.works",
  creator: {
    name: "Sehaj",
    url: "https://sehaj.works",
  },
  ogImage: "https://sehaj.works/meta_thumb2.png",
  links: {
    x: "https://x.com/sehajmakkarr",
    github: "https://github.com/sehajmakkar",
  }
}